# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(862, 587)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(11, 108, 841, 441))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_date = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_date.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_date.setFont(font)
        self.lineEdit_date.setInputMask("")
        self.lineEdit_date.setText("")
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 10, 131, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(9)
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_Search.setAutoRepeatDelay(300)
        self.pushButton_Search.setAutoRepeatInterval(100)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.horizontalLayout.addWidget(self.pushButton_Search)
        self.pushButton_Exit = QtWidgets.QPushButton(self.tab)
        self.pushButton_Exit.setGeometry(QtCore.QRect(730, 370, 75, 23))
        self.pushButton_Exit.setAutoRepeat(False)
        self.pushButton_Exit.setAutoRepeatInterval(101)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.listWidget_box = QtWidgets.QListWidget(self.tab)
        self.listWidget_box.setGeometry(QtCore.QRect(240, 90, 161, 261))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_box.setFont(font)
        self.listWidget_box.setObjectName("listWidget_box")
        self.listWidget_audi = QtWidgets.QListWidget(self.tab)
        self.listWidget_audi.setGeometry(QtCore.QRect(530, 90, 101, 261))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_audi.setFont(font)
        self.listWidget_audi.setObjectName("listWidget_audi")
        self.listWidget_sales = QtWidgets.QListWidget(self.tab)
        self.listWidget_sales.setGeometry(QtCore.QRect(410, 90, 111, 261))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_sales.setFont(font)
        self.listWidget_sales.setObjectName("listWidget_sales")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(240, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setMidLineWidth(0)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(530, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(410, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.listWidget_info = QtWidgets.QListWidget(self.tab)
        self.listWidget_info.setGeometry(QtCore.QRect(640, 90, 181, 261))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕 Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_info.setFont(font)
        self.listWidget_info.setAutoScroll(False)
        self.listWidget_info.setObjectName("listWidget_info")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(640, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(0)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.Label_poster = QtWidgets.QLabel(self.tab)
        self.Label_poster.setGeometry(QtCore.QRect(10, 50, 221, 301))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(12)
        self.Label_poster.setFont(font)
        self.Label_poster.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_poster.setObjectName("Label_poster")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(470, 350, 160, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.lineEdit_mail_PW = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_mail_PW.setGeometry(QtCore.QRect(410, 190, 281, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(12)
        self.lineEdit_mail_PW.setFont(font)
        self.lineEdit_mail_PW.setInputMask("")
        self.lineEdit_mail_PW.setText("")
        self.lineEdit_mail_PW.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mail_PW.setObjectName("lineEdit_mail_PW")
        self.lineEdit_mail_ID = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_mail_ID.setGeometry(QtCore.QRect(410, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(12)
        self.lineEdit_mail_ID.setFont(font)
        self.lineEdit_mail_ID.setInputMask("")
        self.lineEdit_mail_ID.setText("")
        self.lineEdit_mail_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mail_ID.setObjectName("lineEdit_mail_ID")
        self.lineEdit_mail_address = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_mail_address.setGeometry(QtCore.QRect(410, 240, 281, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(12)
        self.lineEdit_mail_address.setFont(font)
        self.lineEdit_mail_address.setInputMask("")
        self.lineEdit_mail_address.setText("")
        self.lineEdit_mail_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mail_address.setObjectName("lineEdit_mail_address")
        self.lineEdit_mail_address_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_mail_address_2.setGeometry(QtCore.QRect(410, 290, 281, 31))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(12)
        self.lineEdit_mail_address_2.setFont(font)
        self.lineEdit_mail_address_2.setInputMask("")
        self.lineEdit_mail_address_2.setText("")
        self.lineEdit_mail_address_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mail_address_2.setObjectName("lineEdit_mail_address_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(430, 50, 231, 81))
        font = QtGui.QFont()
        font.setFamily("1훈정글북 Regular")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_post = QtWidgets.QLabel(self.tab_2)
        self.label_post.setGeometry(QtCore.QRect(140, 80, 231, 241))
        self.label_post.setText("")
        self.label_post.setObjectName("label_post")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(-10, 0, 881, 601))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(290, 40, 521, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rix개봉박두 B")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_box = QtWidgets.QLabel(Dialog)
        self.label_box.setGeometry(QtCore.QRect(120, 5, 121, 121))
        self.label_box.setText("")
        self.label_box.setObjectName("label_box")
        self.label_6.raise_()
        self.tabWidget.raise_()
        self.label_8.raise_()
        self.label_box.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_Exit.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "박스오피스 영화 상세정보 조회 서비스"))
        self.lineEdit_date.setPlaceholderText(_translate("Dialog", "날짜 입력(yyyymmdd)"))
        self.pushButton_Search.setText(_translate("Dialog", "Search"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.label_2.setText(_translate("Dialog", "오늘의 박스 오피스"))
        self.label_3.setText(_translate("Dialog", "누적 관객수"))
        self.label_4.setText(_translate("Dialog", "누적 매출액"))
        self.label_5.setText(_translate("Dialog", "상세정보"))
        self.Label_poster.setText(_translate("Dialog", "포스터가 출력됩니다."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "검색"))
        self.pushButton.setText(_translate("Dialog", "메일 보내기"))
        self.lineEdit_mail_PW.setPlaceholderText(_translate("Dialog", "PASSWORD"))
        self.lineEdit_mail_ID.setPlaceholderText(_translate("Dialog", "ID"))
        self.lineEdit_mail_address.setPlaceholderText(_translate("Dialog", "MAIL ADDRASS"))
        self.lineEdit_mail_address_2.setPlaceholderText(_translate("Dialog", "MAIL SUBJECT "))
        self.label.setText(_translate("Dialog", "메일 보내기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "메일"))
        self.label_8.setText(_translate("Dialog", "B O X O F F I C E"))


